### ISSUE TITLE
可以教教怎么搞这种吗，我也想自定义

### ISSUE THREAD

**Issue by liu-ce** [kasuie/alist-customize#1]

**Comment by kasuie** [comment]
可能你需要学一下css和js基础，然后针对网页自己写一份样式或者js文件结合[Alist文档](https://alist.nn.ci/zh/config/global.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%B4%E9%83%A8)里的自定义body，自定义头部引入你写的文件就可以让你的样式生效了

**Comment by kasuie** [comment]
> _No description provided._

可能你需要学一下css和js基础，然后针对网页自己写一份样式或者js文件结合[Alist文档](https://alist.nn.ci/zh/config/global.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%B4%E9%83%A8)里的自定义body，自定义头部引入你写的文件就可以让你的样式生效了
